FROM aldsmiranda/php:meuphp18

#ADD ssl.conf /etc/apache2/sites-enabled/ssl.conf
ADD apache2.conf /etc/apache2/apache2.conf
RUN chmod +x /usr/local/bin/apache2-foreground && a2enmod expires headers mime_magic include

WORKDIR /var/www/html

EXPOSE 80
CMD ["/run.sh"]
